### ISSUE TITLE
Help me set the callback URI properly

### ISSUE THREAD

**Issue by yeasir-bjit** [gyeongmin-lee/Storify#5]
I have tried to implement the authentication part of this repo. I am not able to set the callback uri. So that after successful login the application not be redirected. Can you please help me in this by giving the guideline?

**Comment by ayhamakeed2000** [comment]
Did you find a solution? @yeasir-bjit

**Comment by yeasir-bjit** [comment]
> Did you find a solution? @yeasir-bjit

Yes @ayhamakeed2000. Thank you for your reply. I am closing the ticket
